"""Change student table

Revision ID: 141ee319dbfb
Revises: 73c5465bb88d
Create Date: 2026-02-12 10:29:17.054595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141ee319dbfb'
down_revision: Union[str, Sequence[str], None] = '73c5465bb88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('third_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'third_name')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
