"""Change teacher table

Revision ID: 6b2a44dc6935
Revises: cd639682ea81
Create Date: 2026-01-29 17:20:51.306346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2a44dc6935'
down_revision: Union[str, Sequence[str], None] = 'cd639682ea81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('third_name', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('teachers_name_key'), 'teachers', type_='unique')
    op.create_unique_constraint(None, 'teachers', ['full_name'])
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teachers', type_='unique')
    op.create_unique_constraint(op.f('teachers_name_key'), 'teachers', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('teachers', 'full_name')
    op.drop_column('teachers', 'third_name')
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'last_name')
    # ### end Alembic commands ###
