"""add faculty and department models

Revision ID: 75ce034b8b0e
Revises: 0aa4a7603fc1
Create Date: 2026-01-17 13:06:37.202543

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "75ce034b8b0e"
down_revision: Union[str, Sequence[str], None] = "0aa4a7603fc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
