"""FIx

Revision ID: 83b8f7d66005
Revises: 4c5f86a920b4
Create Date: 2026-02-11 15:15:15.114447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b8f7d66005'
down_revision: Union[str, Sequence[str], None] = '4c5f86a920b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'user_id')
    # ### end Alembic commands ###
