"""Correct add student

Revision ID: ec606df48080
Revises: 97cd74627524
Create Date: 2026-01-18 22:34:11.378136

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec606df48080"
down_revision: Union[str, Sequence[str], None] = "97cd74627524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("student_id_number", sa.String(), nullable=False),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("university", sa.String(), nullable=False),
        sa.Column("specialty", sa.String(), nullable=False),
        sa.Column("student_status", sa.String(), nullable=False),
        sa.Column("education_form", sa.String(), nullable=False),
        sa.Column("education_type", sa.String(), nullable=False),
        sa.Column("payment_form", sa.String(), nullable=False),
        sa.Column("group", sa.String(), nullable=False),
        sa.Column("education_lang", sa.String(), nullable=False),
        sa.Column("faculty", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("semester", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("avg_gpa", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("students")
    # ### end Alembic commands ###
