"""Change user_id

Revision ID: f6010073a06b
Revises: 1c72e4ad8fc0
Create Date: 2026-02-16 16:52:20.526847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6010073a06b'
down_revision: Union[str, Sequence[str], None] = '1c72e4ad8fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_teachers_teacher_id_fkey'), 'group_teachers', type_='foreignkey')
    op.create_foreign_key(None, 'group_teachers', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_teachers', type_='foreignkey')
    op.create_foreign_key(op.f('group_teachers_teacher_id_fkey'), 'group_teachers', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
